name: deploy for dev

on:
    push:
        branches:
            - 'master' # 只针对 dev 分支
        paths:
            - '.github/workflows/*'
            # - '__test__/**' # dev 不需要立即测试
            - 'src/**'
            - 'Dockerfile'
            - 'docker-compose.yml'
            - 'bin/*'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Sync to Gitee # centos7获取github代码老是挂，要通过获取gitee代码来部署，所以要同步Gitee项目的代码
              uses: wearerequired/git-mirror-action@master
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.LWJ_ID_RSA }} # 传私钥
              with:
                  source-repo: git@github.com:lwjmzla/biz-editor-server.git
                  destination-repo: git@gitee.com:jking123/biz-editor-server.git
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.LWJ_ID_RSA}}" > ~/.ssh/id_rsa # secret 在这里配置 https://github.com/imooc-lego/biz-editor-server/settings/secrets
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "119.29.170.43" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh root@119.29.170.43 "
                    # 【注意】用 work 账号登录，手动创建 /home/work/imooc-lego 目录
                    # 然后 git clone https://username:password@github.com/imooc-lego/biz-editor-server.git -b dev （私有仓库，使用 github 用户名和密码）
                    # 记得删除 origin ，否则会暴露 github 密码

                    cd /home/work/biz-editor-server;
                    git remote add origin https://13535123588:${{secrets.GITEE_LWJ_PASSWORD}}@gitee.com/jking123/biz-editor-server.git;
                    # git checkout dev;
                    git pull; # 重新下载最新代码
                    git checkout remotes/origin/master;
                    # 启动 docker
                    docker-compose build editor-server; # 和 docker-compose.yml service 名字一致
                    git checkout master;
                    git remote remove origin; # 删除 origin ，否则会暴露 github 密码
                    docker-compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa